name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Install dependencies
        run: bun install

      - name: Biome check
        run: bun run check

      - name: Build (node target)
        run: bun build src/index.ts --outdir dist --target node
